@startuml mastermind_clases

class Mastermind{
    - playGames()
}

class Game {
    - int MAX_ATTEMPS = 10
    - string propousalsCombinations[]
    - isWinner()
    - isLooser()
    - isFinished()
    - addPropouseCombination()
    - getResult()
    - getMaxAttemps()
    - getAttemps()
    - getPropousalsCombinations()
}

class GameView{
    - playGames()
    - isResumed()
    - playGame()
}

class TurnView{
    - numPlayers
    - interact(numPlayer)
    - initPlayers()
}

class Turn{
    - reset()
    - getNext()
    - getActivePlayer()
}

class BoardView{
    - showTitle()
    - showIt()
    - showResult()
}

class YesNoDialogView{
    - isAfirmative()
    - isNegative()
}

class GameMode{
    - numPlayers
    - possibleModes
    - MIN
    - MAX
    - read()
}

class ClosedInterval{
    - min
    - max
    - isIncluded()
}

class Combination{
    - int COMBINATION_LENGTH = 4
    - string POSSIBLE_COLORS = "rgbypw"
    - int hasValidLength()
    - boolean hasValidColors()
    - boolean hasRepetedColors()
    - string getPossibleColors()
    - int getCombinationLength()
    - read()

} 
class SecretCombination{
    - read(player)
    - getSecretCombination()
}
class PropousalCombination{
    - read(player)
    - getPropousalCombination()
}

class Player{}
class RandomPlayer{}
class HumanPlayer{}

Mastermind *-down-> GameView
Mastermind *-down-> Game

GameView *-down-> BoardView
GameView *-down-> TurnView
GameView .-down-> Game
GameView *-down-> YesNoDialogView

TurnView *-down-> Turn
TurnView .-down-> BoardView
TurnView *-down-> GameMode
TurnView .-down-> Combination
TurnView .-down-> Player

BoardView .-down-> Game

Player <|-down- RandomPlayer
Player <|-down- HumanPlayer

Combination <|-down- SecretCombination
Combination <|-down- PropousalCombination

GameMode *-down-> ClosedInterval
@enduml