@startuml mastermind_clases

class Mastermind{
    - playGames()
}

class Game {
    - int MAX_ATTEMPS = 10
    - string propousalsCombinations[]
    - isWinner()
    - isLooser()
    - isFinished()
    - addPropouseCombination()
    - getResult()
    - getMaxAttemps()
    - getAttemps()
    - getPropousalsCombinations()
}

class GameView{
    - playGames()
    - isResumed()
    - playGame()
}

class TurnView{
    - readNumPlayers()
    - interact()
}

class Turn{
    - reset()
    - getNext()
}

class BoardView{
    - showTitle()
    - showIt()
    - showResult()
}

class ContinueDialogView{
    - isAfirmative()
    - isNegative()
}

class Combination{
    - int COMBINATION_LENGTH = 4
    - string POSSIBLE_COLORS = "rgbypw"
    - int hasValidLength()
    - boolean hasValidColors()
    - boolean hasRepetedColors()
    - string getPossibleColors()
    - int getCombinationLength()

} 
class SecretCombination{
    - getSecretCombination()
}
class PropousalCombination{
    - getPropousalCombination()
}

class Player{}
class RandomPlayer{}
class HumanPlayer{}

Mastermind *-down-> GameView
Mastermind *-down-> Game

GameView *-down-> BoardView
GameView *-down-> TurnView
GameView .-down-> Game
GameView .-down-> ContinueDialogView

TurnView *-down-> Turn
TurnView *-down-> Player
TurnView .-down-> BoardView
TurnView .-down-> Game

Game .-down-> Combination

BoardView .-down-> Game

Player <|-down- RandomPlayer
Player <|-down- HumanPlayer

RandomPlayer *-down-> SecretCombination

HumanPlayer *-down-> PropousalCombination

Combination <|-down- SecretCombination
Combination <|-down- PropousalCombination
@enduml